"""PhysX-only stepping bridge. Run INSIDE the pinned Isaac Sim 4.5 container.

MuJoCo is not imported here: JSON contains physical parameters and NPZ contains
controller reference/feedforward inputs. Every state is generated by PhysX.
"""
import argparse
import hashlib
import json
import os
import sys
from pathlib import Path
import time
import traceback

import numpy as np


def arguments():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--inputs", type=Path, default=Path("/work/isaac/inputs"))
    p.add_argument("--out", type=Path, default=Path("/work/results/isaac"))
    p.add_argument("--variants", nargs="+", choices=["nom", "ref"], default=["nom", "ref"])
    p.add_argument("--tasks", nargs="+", default=["seed1", "seed2", "seed3", "seed11", "seed12", "press"])
    p.add_argument("--overwrite", action="store_true")
    return p.parse_args()


def build_stage(stage, config, variant, contact):
    from pxr import Gf, UsdGeom, UsdPhysics, PhysxSchema, UsdShade
    def vec(v):
        return Gf.Vec3f(*map(float, v))
    def quat(v):
        return Gf.Quatf(float(v[0]), vec(v[1:]))
    UsdGeom.SetStageUpAxis(stage, UsdGeom.Tokens.z)
    UsdGeom.SetStageMetersPerUnit(stage, 1.0)
    UsdPhysics.SetStageKilogramsPerUnit(stage, 1.0)
    root = "/World/FR3"
    UsdGeom.Xform.Define(stage, "/World")
    UsdGeom.Xform.Define(stage, root)
    model = config["nominal" if variant == "nom" else "reference"]
    for b in model["bodies"]:
        body = UsdGeom.Xform.Define(stage, root + "/" + b["name"])
        body.AddTranslateOp().Set(Gf.Vec3d(*b["position"]))
        body.AddOrientOp().Set(quat(b["orientation"]))
        UsdPhysics.RigidBodyAPI.Apply(body.GetPrim())
        rb = PhysxSchema.PhysxRigidBodyAPI.Apply(body.GetPrim())
        rb.CreateLinearDampingAttr(0.0)
        rb.CreateAngularDampingAttr(0.0)
        rb.CreateMaxAngularVelocityAttr(10000.0)
        mass = UsdPhysics.MassAPI.Apply(body.GetPrim())
        mass.CreateMassAttr(b["mass"])
        mass.CreateCenterOfMassAttr(vec(b["com"]))
        mass.CreateDiagonalInertiaAttr(vec(b["inertia"]))
        mass.CreatePrincipalAxesAttr(quat(b["inertia_quat"]))
    fixed = UsdPhysics.FixedJoint.Define(stage, root + "/base_fixed")
    fixed.CreateBody1Rel().SetTargets([root + "/fr3_link0"])
    # Root must be on the world-fixed joint or its ancestor, NOT on the base
    # rigid body (which would create a floating articulation held by a constraint).
    root_prim = stage.GetPrimAtPath(root)
    UsdPhysics.ArticulationRootAPI.Apply(root_prim)
    art = PhysxSchema.PhysxArticulationAPI.Apply(root_prim)
    art.CreateEnabledSelfCollisionsAttr(False)
    art.CreateSolverPositionIterationCountAttr(config["position_iterations"])
    art.CreateSolverVelocityIterationCountAttr(config["velocity_iterations"])
    art.CreateSleepThresholdAttr(0.0)
    art.CreateStabilizationThresholdAttr(0.0)
    for j in model["joints"]:
        joint = UsdPhysics.RevoluteJoint.Define(stage, root + "/" + j["name"])
        joint.CreateBody0Rel().SetTargets([root + "/" + j["parent"]])
        joint.CreateBody1Rel().SetTargets([root + "/" + j["child"]])
        joint.CreateAxisAttr("Z")
        joint.CreateLocalPos0Attr(vec(j["position"]))
        joint.CreateLocalRot0Attr(quat(j["orientation"]))
        joint.CreateLocalPos1Attr(vec([0, 0, 0]))
        joint.CreateLocalRot1Attr(quat([1, 0, 0, 0]))
        joint.CreateLowerLimitAttr(float(np.degrees(j["limits"][0])))
        joint.CreateUpperLimitAttr(float(np.degrees(j["limits"][1])))
        api = PhysxSchema.PhysxJointAPI.Apply(joint.GetPrim())
        api.CreateJointFrictionAttr(0.0)
        api.CreateArmatureAttr(j["armature"])
        api.CreateMaxJointVelocityAttr(float(np.degrees(10.0)))
        # No joint drives: all actuation and passive friction are SI efforts.
    if contact:
        material = UsdShade.Material.Define(stage, "/World/contact_material")
        mat = UsdPhysics.MaterialAPI.Apply(material.GetPrim())
        mu = 0.6 if variant == "nom" else 0.3
        mat.CreateStaticFrictionAttr(mu)
        mat.CreateDynamicFrictionAttr(mu)
        mat.CreateRestitutionAttr(0.0)
        sphere = UsdGeom.Sphere.Define(stage, root + "/fr3_link7/probe")
        sphere.CreateRadiusAttr(config["probe_radius"])
        sphere.AddTranslateOp().Set(Gf.Vec3d(*config["probe_local"]))
        cube = UsdGeom.Cube.Define(stage, "/World/plate")
        cube.CreateSizeAttr(2.0)
        center = np.array(config["plate_top"])
        center[2] -= config["plate_half"][2]
        cube.AddTranslateOp().Set(Gf.Vec3d(*center))
        cube.AddScaleOp().Set(Gf.Vec3f(*config["plate_half"]))
        for shape in (sphere, cube):
            UsdPhysics.CollisionAPI.Apply(shape.GetPrim())
            col = PhysxSchema.PhysxCollisionAPI.Apply(shape.GetPrim())
            col.CreateContactOffsetAttr(config["contact_offset"])
            col.CreateRestOffsetAttr(config["rest_offset"])
            UsdShade.MaterialBindingAPI.Apply(shape.GetPrim()).Bind(material, materialPurpose="physics")
    return model


def world_point(position, orientation, local):
    w, x, y, z = orientation
    rot = np.array([[1-2*(y*y+z*z), 2*(x*y-z*w), 2*(x*z+y*w)],
                    [2*(x*y+z*w), 1-2*(x*x+z*z), 2*(y*z-x*w)],
                    [2*(x*z-y*w), 2*(y*z+x*w), 1-2*(x*x+y*y)]])
    return position + rot @ local


def collect_one(app, args, config, variant, task):
    from isaacsim.core.api import World
    from isaacsim.core.prims import SingleArticulation, RigidPrim
    from isaacsim.core.utils.stage import create_new_stage
    from pxr import PhysxSchema
    path = args.out / f"{variant}_{task}.npz"
    if path.exists() and not args.overwrite:
        raise FileExistsError(f"Refusing to overwrite {path}; use a new output directory or --overwrite")
    entry = config["trajectories"][task]
    trajpath = args.inputs / entry["file"]
    if hashlib.sha256(trajpath.read_bytes()).hexdigest() != entry["sha256"]:
        raise ValueError(f"Trajectory hash mismatch: {trajpath}")
    tr = dict(np.load(trajpath, allow_pickle=False))
    dt, h = config["dt_control"], config["dt_physics"]
    nsub = round(dt / h)
    if abs(nsub * h - dt) > 1e-10:
        raise ValueError("Physics timestep must divide the control timestep")
    World.clear_instance()
    create_new_stage()
    world = World(physics_dt=h, rendering_dt=dt, stage_units_in_meters=1.0, backend="numpy", device="cpu")
    context = world.get_physics_context()
    context.set_gravity(-9.81)
    context.set_solver_type(config["solver"])
    context.enable_gpu_dynamics(False)
    context.set_broadphase_type("MBP")
    model = build_stage(world.stage, config, variant, task == "press")
    robot = world.scene.add(SingleArticulation(prim_path="/World/FR3", name="fr3"))
    link = world.scene.add(RigidPrim(prim_paths_expr="/World/FR3/fr3_link7", name="flange",
                                     track_contact_forces=task == "press", reset_xform_properties=False))
    world.reset()
    if robot._articulation_view.get_mass_matrices().shape != (1, 7, 7):
        raise RuntimeError("Expected fixed-base 7-DoF articulation, not a constrained floating base")
    expected = [j["name"] for j in model["joints"]]
    if set(robot.dof_names) != set(expected):
        raise RuntimeError(f"Unexpected DOFs: {robot.dof_names}")
    order = np.array([robot.get_dof_index(j) for j in expected])
    # Audit the authored inertias/armature and export the exact executable world.
    arm = [PhysxSchema.PhysxJointAPI(world.stage.GetPrimAtPath('/World/FR3/' + j)).GetArmatureAttr().Get() for j in expected]
    if not np.allclose(arm, [j["armature"] for j in model["joints"]], rtol=1e-6):
        raise RuntimeError("Armature write-back failed")
    # PhysX tensor FK must agree before trusting any simulation output.
    fk_errors = []
    for check in model["fk_checks"]:
        robot.set_joint_positions(np.array(check["q"]), joint_indices=order)
        pos, ori = link.get_world_poses()
        tcp = world_point(pos[0], ori[0], np.array(config["tcp_local"]))
        fk_errors.append(float(np.linalg.norm(tcp - check["tcp"])))
    if max(fk_errors) > 2e-5:
        raise RuntimeError(f"PhysX/MuJoCo FK mismatch [m]: {fk_errors}")
    robot.set_joint_positions(tr["q_d"][0], joint_indices=order)
    robot.set_joint_velocities(np.zeros(7), joint_indices=order)
    robot.set_joint_efforts(np.zeros(7), joint_indices=order)
    world.stage.Export(str(args.out / f"{variant}_{'plate' if task == 'press' else 'free'}.usda"))
    n = len(tr["t"])
    Q, QD, TAU, NET, PASSIVE = [np.zeros((n, 7)) for _ in range(5)]
    F, P = np.zeros(n), np.zeros((n, 3))
    coul = np.array([j["coulomb"] for j in model["joints"]])
    visc = np.array([j["viscous"] for j in model["joints"]])
    last_force = 0.0
    start = time.monotonic()
    for k in range(n):
        q = robot.get_joint_positions()[order].astype(float)
        qd = robot.get_joint_velocities()[order].astype(float)
        tau = np.clip(tr["tau_ff"][k] + tr["kp"] * (tr["q_d"][k]-q) + tr["kd"] * (tr["qd_d"][k]-qd),
                      -tr["tau_lim"], tr["tau_lim"])
        if not (np.isfinite(q).all() and np.isfinite(qd).all()) or np.max(np.abs(q - tr["q_d"][k])) > 0.75:
            raise RuntimeError(f"Unstable rollout {variant}/{task}, step {k}, q={q}, qd={qd}")
        Q[k], QD[k], TAU[k], F[k] = q, qd, tau, last_force
        pos, ori = link.get_world_poses()
        P[k] = world_point(pos[0], ori[0], np.array(config["tcp_local"]))
        friction = coul * np.tanh(qd / config["friction_velocity"]) + visc * qd
        PASSIVE[k], NET[k] = friction, tau - friction
        forces = []
        for _ in range(nsub):
            vel = robot.get_joint_velocities()[order].astype(float)
            passive = coul * np.tanh(vel / config["friction_velocity"]) + visc * vel
            robot.set_joint_efforts(tau - passive, joint_indices=order)
            world.step(render=False)
            if task == "press":
                forces.append(float(abs(link.get_net_contact_forces(dt=h)[0, 2])))
        last_force = float(np.mean(forces)) if forces else 0.0
        if k % 2000 == 0:
            print(f"ISAAC {variant}/{task}: {k}/{n}, wall {time.monotonic()-start:.1f}s, max error {np.max(np.abs(q-tr['q_d'][k])):.4f} rad", flush=True)
    metadata = dict(schema_version=2, engine=config["engine"], variant=variant, task=task, fixed_base=True,
                    sample_convention="q,qd,tau at pre-step t[k]; F is mean normal force of preceding control interval",
                    dt_control=dt, dt_physics=h, native_armature=arm, friction_mode=config["friction_mode"],
                    friction_velocity=config["friction_velocity"], physics_device="cpu", solver=config["solver"],
                    fk_error_m=fk_errors, dof_names=expected,
                    manifest_sha256=hashlib.sha256((args.inputs / "manifest.json").read_bytes()).hexdigest(),
                    trajectory_sha256=entry["sha256"], wall_seconds=time.monotonic()-start)
    # Atomic commit; a failed run never leaves a seemingly complete NPZ.
    temp = path.with_suffix(".tmp.npz")
    np.savez_compressed(temp, t=tr["t"], q=Q, qd=QD, tau=TAU, tau_net=NET, tau_passive=PASSIVE,
                        q_ref=tr["q_d"], F=F, p=P, kp=tr["kp"], kd=tr["kd"], tau_lim=tr["tau_lim"],
                        metadata=np.array(json.dumps(metadata)))
    temp.replace(path)
    path.with_suffix(".json").write_text(json.dumps(metadata, indent=2))
    print(f"SAVED {path} ({time.monotonic()-start:.1f}s)", flush=True)
    world.stop()


def main():
    args = arguments()
    config = json.loads((args.inputs / "manifest.json").read_text())
    if config.get("schema_version") != 2 or not config.get("fixed_base"):
        raise ValueError("Regenerate inputs using the current prepare.py (fixed-base schema 2)")
    for task in args.tasks:
        if task not in config["trajectories"]:
            raise ValueError(f"Unknown task: {task}")
    args.out.mkdir(parents=True, exist_ok=True)
    from isaacsim import SimulationApp
    app = SimulationApp({"headless": True, "width": 64, "height": 64,
                         "anti_aliasing": 0, "hide_ui": True, "multi_gpu": False, "fast_shutdown": True},
                        experience=str(Path(__file__).with_name("physics.kit")))
    try:
        for variant in args.variants:
            for task in args.tasks:
                collect_one(app, args, config, variant, task)
    except BaseException:
        traceback.print_exc()
        # Kit fast shutdown otherwise masks Python failures with exit status 0.
        # The disposable container reclaims resources; no incomplete NPZ is committed.
        sys.stdout.flush()
        sys.stderr.flush()
        os._exit(1)
    finally:
        app.close()


if __name__ == "__main__":
    main()
